// Auto-generated by fit_bc_aus_by_zone.py - DO NOT EDIT BY HAND.
// Re-run `python3 fit_bc_aus_by_zone.py` to regenerate.
//
// Separate five-parameter Burch-Christensen fits for each AS/NZS 4234
// climate zone. This is the regional version of BC-Aus.
// Generated: 2026-04-14T14:35:00
// Overall RMSE across all 5 zones: 0.705 degC
const BC_AUS_ZONE_CONSTANTS = {
  zone1: {
    name: "Zone 1 — Alice Springs",
    city: "Alice Springs",
    offsetF: 8.08374694,
    ratioC0: 0.98902166,
    ratioC1: -0.02127621,
    lagC0: 42.50534081,
    lagC1: -2.00087124,
    rmseC: 0.697226,
  },
  zone2: {
    name: "Zone 2 — Rockhampton",
    city: "Rockhampton",
    offsetF: -3.13232367,
    ratioC0: 1.00129389,
    ratioC1: 0.03030210,
    lagC0: 42.00526458,
    lagC1: -1.85642713,
    rmseC: 0.950095,
  },
  zone3: {
    name: "Zone 3 — Sydney",
    city: "Sydney",
    offsetF: -0.37705119,
    ratioC0: 0.80057423,
    ratioC1: 0.01158591,
    lagC0: 39.97591642,
    lagC1: -1.98585011,
    rmseC: 0.601931,
  },
  zone4: {
    name: "Zone 4 — Melbourne",
    city: "Melbourne",
    offsetF: -0.82216746,
    ratioC0: 0.80077479,
    ratioC1: 0.01155877,
    lagC0: 39.92431791,
    lagC1: -2.62910112,
    rmseC: 0.501776,
  },
  zone5: {
    name: "Zone 5 — Canberra",
    city: "Canberra",
    offsetF: 0.04457657,
    ratioC0: 1.00083512,
    ratioC1: 0.00311399,
    lagC0: 42.09699593,
    lagC1: -1.05763617,
    rmseC: 0.693906,
  },
};

const BC_AUS_ZONE_OVERALL_RMSE_C = 0.705000;
