// Hybrid golden/reference checks for solar geometry, isotropic POA, and PV-only output.
// Reference values in validation/reference/reference_summary.json were generated by pvlib.
import fs from "node:fs";

class TiltedSurfaceRadiation {
  constructor(latitude, longitude, tiltAngle, surfaceAzimuth, albedo = 0.2){
    this.latitude = latitude; this.longitude = longitude;
    this.tiltAngle = tiltAngle; this.surfaceAzimuth = surfaceAzimuth; this.albedo = albedo;
  }
  toRadians(deg){ return deg * Math.PI / 180; }
  toDegrees(rad){ return rad * 180 / Math.PI; }
  declinationAngle(dayN){ return 23.45 * Math.sin(this.toRadians((360 / 365) * (dayN + 284))); }
  hourAngle(hourN){ return 15 * (hourN - 12); }
  zenithAngle(dayN, hourN){
    const d = this.toRadians(this.declinationAngle(dayN));
    const w = this.toRadians(this.hourAngle(hourN));
    const L = this.toRadians(this.latitude);
    return this.toDegrees(Math.acos(Math.min(1, Math.max(-1, Math.sin(d)*Math.sin(L)+Math.cos(d)*Math.cos(L)*Math.cos(w)))));
  }
  incidenceAngle(dayN, hourN){
    const d=this.toRadians(this.declinationAngle(dayN)), w=this.toRadians(this.hourAngle(hourN));
    const L=this.toRadians(this.latitude), s=this.toRadians(this.tiltAngle), g=this.toRadians(this.surfaceAzimuth-180);
    const i1=Math.sin(d)*Math.sin(L)*Math.cos(s), i2=Math.sin(d)*Math.cos(L)*Math.sin(s)*Math.cos(g);
    const i3=Math.cos(d)*Math.cos(L)*Math.cos(s)*Math.cos(w), i4=Math.cos(d)*Math.sin(L)*Math.sin(s)*Math.cos(g)*Math.cos(w);
    const i5=Math.cos(d)*Math.sin(s)*Math.sin(g)*Math.sin(w);
    return this.toDegrees(Math.acos(Math.min(1, Math.max(-1, i1-i2+i3+i4+i5))));
  }
  calculate(dayN, hourN, dni, dhi){
    const thetaZ=this.zenithAngle(dayN,hourN), cosThetaZ=Math.cos(this.toRadians(thetaZ)), eps=1e-6;
    const DNI=Math.max(0,dni||0), DHI=Math.max(0,dhi||0);
    const BHI=(cosThetaZ>eps)?DNI*Math.max(0,cosThetaZ):0, ghi=BHI+DHI;
    const thetaT=this.incidenceAngle(dayN,hourN), cosThetaT=Math.cos(this.toRadians(thetaT));
    const beam=(cosThetaZ>eps)?DNI*Math.max(0,cosThetaT):0;
    const diffuse=DHI*((1+Math.cos(this.toRadians(this.tiltAngle)))/2);
    const ground=ghi*this.albedo*((1-Math.cos(this.toRadians(this.tiltAngle)))/2);
    return { totalIrradiance: Math.max(0, beam+diffuse+ground) };
  }
}

const finite = x => typeof x === "number" && Number.isFinite(x);
const refs = JSON.parse(fs.readFileSync(new URL("../reference/reference_summary.json", import.meta.url), "utf8"));
let pass = 0, fail = 0;
function ok(name, cond, detail=""){
  if (cond){ pass++; console.log(`  PASS  ${name}`); }
  else { fail++; console.log(`  FAIL  ${name}${detail ? "  " + detail : ""}`); }
}

console.log("\n# PVLIB GOLDEN REFERENCE - ISOTROPIC CORE MODEL");
for (const [cityName, ref] of Object.entries(refs)){
  const slug = cityName.toLowerCase();
  const fixture = JSON.parse(fs.readFileSync(new URL(`../fixtures/backend/backend_${slug}.json`, import.meta.url), "utf8"));
  const calc = new TiltedSurfaceRadiation(fixture.lat, fixture.lon, fixture.tilt, 0, fixture.albedo);
  let annualPoaWhM2 = 0;
  for (const raw of fixture.records){
    let hourN = raw.hourN;
    if (finite(hourN) && hourN >= 1 && hourN <= 24) hourN -= 1;
    const solarH = finite(+raw.solarHour) ? +raw.solarHour : hourN;
    if (![raw.dayN, solarH, raw.dni, raw.dhi].every(finite)) continue;
    annualPoaWhM2 += calc.calculate(raw.dayN, solarH, raw.dni, raw.dhi).totalIrradiance;
  }
  const poaKWhM2 = annualPoaWhM2 / 1000;
  const pvKWh = poaKWhM2 * fixture.area * fixture.eta;
  const poaErrPct = (poaKWhM2 / ref.ref_annual_poa_kwh_m2 - 1) * 100;
  const pvErrPct = (pvKWh / ref.ref_isotropic_annual_kwh - 1) * 100;
  ok(`${cityName}: POA within 0.2% of pvlib isotropic`, Math.abs(poaErrPct) <= 0.2, `err=${poaErrPct.toFixed(3)}%`);
  ok(`${cityName}: PV-only annual kWh within 0.2% of pvlib`, Math.abs(pvErrPct) <= 0.2, `err=${pvErrPct.toFixed(3)}%`);
  ok(`${cityName}: Perez remains benchmark-only`, ref.ref_perez_annual_kwh > ref.ref_isotropic_annual_kwh, "Perez should not replace isotropic default");
}

console.log(`\n=== ${pass} passed, ${fail} failed ===`);
process.exit(fail === 0 ? 0 : 1);
